### ISSUE TITLE
Functionality Checklist

### ISSUE THREAD

**Issue by sarakkal107** [allends/cs336final#1]
1. Auctions
    - [x] Seller creates auction and posts items for sale
        - [x] Set all characteristics of the item
        - [x] Set closing date and time
        - [x] Set a hidden minimum price (reserve)
    - [x] A buyer is able to bid
        - [x] Let the buyer set a new bid
        - [ ] In case of automatic bidding set secret upper limit and bid increment
        - [x] Alert other buyers of the item that a higher bid has been placed (manual)
        - [ ] Alert buyers in case some bids more than their upper limit (automatic)
    - [x] Define the winner of the auction
        - [x] When the closing time has come, check if the seller has set a reserve
            - [x] Yes: If the reserve is higher than the last bid no one is the winner
            - [x] No: Whoever has the highest bid is the winner
                - [x] Alert the winner
                
  

2. Browsing and Advanced Search
    - [x] Let people browse on the items and see the status of the current bidding
    - [x] Sort by different criteria (by type, bidding price, etc.)
    - [x] Search the list of items by various criteria
    - [x] A user should be able to
        - [x] View all the history of bids for any specific auction
        - [x] View the list of all auctions a specific buyer or seller has participated in
        - [ ] View the list of "similar" items on auctions in the preceding month (and info about them)
    - [ ] Let user set an alert for specific items they are interested in
        - [ ] Get an alert when the item becomes available
    - [x] Users browse questions and answers
    - [x] Users search questions by keywords

3. Admin and Customer Rep
     - [x] Admin (predefined)
        - [x] Creates accounts for customer representatives
        - [x] Generates sales reports for:
            - [x] Total Earnings
            - [x] Earnings Per:
                - [x] Item
                - [x] Item Type
                - [x] End-User
            - [x] Best-selling items
            - [x] best buyers 
     - [x] Customer Representative Functions
        - [x] Users post questions to customer representatives
        - [x] Reps reply to user questions
        - [x] Edits and deletes account info
        - [x] Remove bids
        - [x] Remove auctions

**Comment by eoinoh15** [comment]
Change
